apiVersion: v1

kind: PersistentVolumeClaim

metadata:

  name: docker-pv-claim

  labels:

    app: docker

spec:

  accessModes:

    - ReadWriteOnce

  volumeMode: Filesystem

  storageClassName: gp2

  resources:

    requests:

      storage: 1Gi
