apiVersion: apps/v1

kind: ReplicaSet

metadata:

  name: docker

  namespace: mohammedsalemabdellahi

  labels:

    app: docker

    version: 0.0.3

spec:

  replicas: 3

  selector:

    matchLabels:

      app: docker

  template:

    metadata:

      name: docker

      labels:

        app: docker

        version: 0.0.3

    spec:

      containers:

      - name: docker

        image: docker: 0.0.3

        resources:

          requests:

            memory: "64Mi"

            cpu: "250m"

          limits:

            memory: "64Mi"

            cpu: "250m"

        ports:

        - containerPort: 80

        volumeMounts:          

        - name: data-volume

          mountPath: /tmp/data  

  volumes:                     

  - name: data-volume

    persistentVolumeClaim:

      claimName: my-pvc
